<body>
    <div>
        

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-12 col-xs-12">
                        <h4 class="page-title">User <?php echo $this->userid['user_id']; ?>  IN Game 6 Detail</h4>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>

                <!-- .row -->
                <div class="row">
                    <div class="col-xs-12">
						<div class="flex-grid full-visitor-journey">
							<div class="flex-col full-visitor-journey-map">
								<ul class="list-unstyled">
									<?php 
										foreach ($this->log_date as $value) { ?>					
										<li>											
										<h4> <?php echo  date('j F Y', strtotime( $value['dates'])); ?></h4>
											<?php 
											foreach ($this->log_time as $key => $time) {

												foreach ($time as $times) {
													if($value['dates'] == $key ){?>
													<ul class="list-unstyled">
														<li class="active"><?php echo  date("H:i:s",strtotime($times));  ?></li>
													</ul>
													<?php
												}
												}
											}  ?>
										</li>
								<?php }?>
									
								</ul>
							</div>
							<div class="flex-col full-visitor-journey-details">
								<?php 
	                    			foreach ($this->rates_log as $key => $time) {
												foreach ($time as  $values) { 
	                    					?>
	                    		<div class="white-box">
		                        	<ul class="timeline journey-timeline">
		                        		<li>
		                        			<div class="timeline-panel timeline-start">              			
		                                        <div class="timeline-heading">
			                        				<h3 class="pull-left"><?php  echo  date("h:i A  d F, Y ",strtotime( $values['start_time'])) ?> </h3>
			                        				<p class="pull-right"><?php echo $values['image_view_log'] ?> Image views + <?php echo $values['share_count'] ?> Shares</p>
		                                        </div>		                                   
		                        			</div>
		                        		</li>
		                        		  <?php 
		                        		  		
		                        				foreach ($values['rounds'] as $roundkey=> $ratevalue) {
		                        		// print_r($ratevalue);				
		                        				
		                                	?>
		                                <li>
		                              
		                                    <div class="timeline-panel">
		                                        <div class="timeline-overview">Round <?php echo $roundkey;?> (<?php echo count($ratevalue['viewed']) ?>  Images + <?php echo count($ratevalue['shared']) ?> Share)</div>

		                                     <?php  ?>
		                                        <div class="timeline-body">

		                                            <div class="visitor-jry-details">
		                                      		
		                                            	<div class="white-box">
		                                            		<ul class="list-inline game-image-list">
		                                            		 <?php 	foreach ($ratevalue['data'] as $r1) {

		                                            		  ?>
		                                            			<li>
		                                            		
		                                            				<div class="round-img">
		                                            					<img src="<?php echo $r1['image_url'] ?>" class="img-responsive">
		                                            				</div>
		                                            				<div class="round-rating">
		                                            					<ul class="list-unstyled">
		                                            						<li>AI Rating:  <strong>0.8</strong></li>
		                                            						<li>User Rating:  <strong><?php echo $r1['rate'] ?></strong></li>
		                                            					</ul>
		                                            				</div>
		                                            				<?php if($r1['shared']>0){ ?>
		                                            				<div class="round-shared"><i class="fa fa-share-alt"></i></div>
		                                            			<?php  }?>
		                                            			</li>
		                                            			 <?php } ?>
		                                            		</ul>

		                                            	</div>
		                                            	
		                                            </div>
		                                           
		                                        </div>
		                                        <?php   ?>
		                                    </div>
		                                </li>
		                            <?php
		                        
		                           
		                        }
		                    	 ?>
		                            </ul>
		                          
	                        	</div>
	                        	 <?php  }
		                        }
		                          ?>   
	                        </div>
	                    </div>
	                </div>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Events Modal -->
	<div class="modal fade" id="events-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	    <div class="modal-dialog" role="document">
	        <div class="modal-content">
	            <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	                <h4 class="modal-title" id="myModalLabel">Visitor Events Tracking</h4>
	            </div>
	            <div class="modal-body">
	            	<table class="table">
	            		<thead>
	            			<tr>
	            				<th>Time</th>
	            				<th>Category</th>
	            				<th>Action</th>
	            				<th>Label</th>
	            			</tr>
	            		</thead>
	            		<tbody>
	            			<tr>
	            				<td>03:00:00</td>
	            				<td>phone_no_clicked</td>
	            				<td>Phone_No_Button_Clicked</td>
	            				<td>PhoneNoClicked</td>
	            			</tr>
	            		</tbody>
	            	</table>
	            </div>
	        </div>
	    </div>
	</div>

    
</body>