<body>
    <div>
        <!-- Navigation, Sidebar and Menues -->
       

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <h4 class="page-title">User <?php echo $this->userdetails['id'] ?> IN Overview</h4>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    	<a href="users/addnew" class="btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm">Add New User</a>
                    	<a href="users/edituser?id=<?php echo $this->userdetails['id'];?>" class="btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm">Edit User</a>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>

                <div class="row">
                    <div class="col-md-2 col-xs-12 col-sm-6">
                        <div class="white-box text-right bg-warning" title="Games played by user in total" data-toggle="tooltip" data-placement="bottom">
                        	<p class="text-white text-left"><i class="ti-video-clapper fa-2x"></i></p>
                            <h1 class="text-white counter"><?php echo $this->userdetails['games_played']  ?></h1>
                            <p class="text-white">Games</p>
                        </div>
                    </div>
                    <div class="col-md-2 col-xs-12 col-sm-6">
                        <div class="white-box text-right bg-info" title="Quality of the results from the image search engine in total" data-toggle="tooltip" data-placement="bottom">
                        	<p class="text-white text-left"><i class="ti-cup fa-2x"></i></p>
                            <h1 class="text-white counter">50</h1>
                            <p class="text-white">Quality</p>
                        </div>
                    </div>
                    <div class="col-md-2 col-xs-12 col-sm-6">
                        <div class="white-box text-right" title="Time spent overall" data-toggle="tooltip" data-placement="bottom">
                        	<p class="text-muted text-left"><i class="ti-time fa-2x"></i></p>
                            <h1 class="counter"><?php echo gmdate("H:i:s",$this->userdetails['total_time_spent']); ?></h1>
                            <p class="text-muted">Duration</p>
                        </div>
                    </div>
                    <div class="col-md-2 col-xs-12 col-sm-6">
                        <div class="white-box text-right bg-success" title="How often do users return to the game in total" data-toggle="tooltip" data-placement="bottom">
                        	<p class="text-white text-left"><i class="ti-mouse-alt fa-2x"></i></p>
                            <h1 class="text-white counter"><?php echo $this->userdetails['retention_count']  ?></h1>
                            <p class="text-white">Retention</p>
                        </div>
                    </div>
                    <div class="col-md-2 col-xs-12 col-sm-6">
                        <div class="white-box text-right bg-theme-dark" title="# of images viewed in total" data-toggle="tooltip" data-placement="bottom">
                        	<p class="text-white text-left"><i class="ti-image fa-2x"></i></p>
                            <h1 class="text-white counter"><?php echo $this->userdetails['total_images_view_count']  ?></h1>
                            <p class="text-white">Images</p>
                        </div>
                    </div>
                    <div class="col-md-2 col-xs-12 col-sm-6">
                        <div class="white-box text-right bg-primary" title="# of shares in total" data-toggle="tooltip" data-placement="bottom">
                        	<p class="text-white text-left"><i class="ti-share fa-2x"></i></p>
                            <h1 class="text-white counter"><?php echo $this->userdetails['total_shares']  ?></h1>
                            <p class="text-white">Shares</p>
                        </div>
                    </div>
                </div>

                <!-- .row -->
                <div class="row">
                    <div class="col-xs-12">
                        <div class="white-box">
                        	<div class="visitor-box">
                        		<div class="row">
                        			<div class="col-xs-12">  
                        			</div>
                        		</div>
		                        <div class="row">
									<div class="flex-grid">
										<div class="visitor-general-details-list flex-col">
											<div class="row">
												<div class="col-xs-12">		                        				
									        		<ul class="list-unstyled">
									        			<li><strong>User Id:</strong><?php echo $this->userdetails['id']  ?></li>
									        			<li><strong>Email:</strong> <?php echo $this->userdetails['email']  ?></li>									        			
									        		</ul>	
												</div>
											</div>
										</div>
										<div class="visitor-details-box flex-col">
											<div class="row">
											
												<div class="col-xs-12">
												<?php
												$count = 0;
                                                // if($this->userlogs == ''){
                                                // print_r($this->userlogs);
												foreach($this->userlogs  as $key=>$values){
													$count++;
												?>
													<div class="panel-group visitor-accordian" id="accordion" role="tablist">
													    <div class="panel panel-default">
													        <div class="panel-heading">
													            <h4 class="panel-title">
													                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_<?= $count ?>" aria-expanded="true" aria-controls="collapse_<?= $count ?>" class="collapsed">
													                <?php echo  date('j F Y', strtotime( $key)); ?>
													                	<span class="pull-right"><?php echo count($values) ?> Games <small><?php echo  date("H:i:s",strtotime($key['total_time_spend']));  ?></small></span>
													                </a>
													            </h4>
													        </div>
													        <?php 
													        	
													        ?>
													        
													        <div id="collapse_<?= $count ?>" class="panel-collapse collapse" role="tabpanel">
													            <div class="panel-body">
													                <table class="table">
													                	<thead>
													                		<tr>
													                			<th>Time</th>
													                			<th>Session Time</th>
													                			<th>Rounds</th>
													                			<th>Image Views</th>
													                			<th>Retention Rate</th>
													                			<th>Shares</th>
													                		</tr>
													                	</thead>
													                	<tbody>
                                                                            <?php foreach ($values as $value1) {?>
													                		<tr>
													                			<td><a href="users/gamedetail?user_id=<?php echo $this->userdetails['id']  ?>">
													                				<?php echo  date("H:i:s",strtotime($value1['start_time']));  ?></a></td>
													                			<td>52:60:00</td>
													                			<td><?php echo $value1['rounds']  ?></td>
													                			<td><?php echo $value1['image_view_log'] ?></td>
													                			<td>60%</td>
													                			<td><?php echo $value1['share_count'] ?></td>
													                		</tr>
													                		<?php } ?>
													                	</tbody>
													                </table>
													            </div>
													        </div>
													    <?php }  ?>
													    </div>
													</div>
													<?php  ?>			                        				
												</div>
												
											</div>
										</div>
									</div>
	                        	</div>
                        	</div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

</body>